version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount the local index_data.db into the container at the same path
      - ./index_data.db:/app/index_data.db
    depends_on:
      - redis
    environment:
      - DATABASE_URL=/app/index_data.db
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"